FROM python:3.12-slim

WORKDIR /app/backend

COPY backend/requirements.txt /app/backend/requirements.txt

RUN pip install --no-cache-dir -r /app/backend/requirements.txt \
    && pip install --no-cache-dir pypdf

COPY backend/app /app/backend/app
COPY documents /app/documents
COPY backend/evaluation_week4 /app/backend/evaluation_week4
COPY backend/evaluation_week5 /app/backend/evaluation_week5
RUN mkdir -p /app/data/uploads

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
